'use client';

// Ref: DESIGN.md §4.3 (Nested Drop Zone), ARCHITECTURE.md §5.1 + §10.
// Drop zone per parent. Only parents valid for the dragged type get
// highlighted (dashed blurple + label). Invalid zones stay plain.

import { useDndContext, useDroppable } from '@dnd-kit/core';
import type { ComponentType } from '@/lib/schema/constants';
import { useDocumentStore } from '@/lib/store/document';
import type { NodeId } from '@/lib/serializer/types';

interface DropZoneProps {
  /** Target parent id. null = root (accepts Container 17 only). */
  parentId: NodeId | null;
  /** Label while a valid zone is hovered. Auto-generated by default. */
  label?: string;
  /** Compact variant for gaps between children. */
  compact?: boolean;
}

/** Read the drag type from dnd-kit without `as` (AGENTS.md §2). */
export function toComponentType(value: unknown): ComponentType | undefined {
  return value === 1 ||
    value === 2 ||
    value === 9 ||
    value === 10 ||
    value === 11 ||
    value === 12 ||
    value === 14 ||
    value === 17
    ? value
    : undefined;
}

/**
 * Type-level check: may childType sit under parentType.
 * Light mirror of assertCanAttach in lib/store/document.ts
 * (capacity limits like 3 texts or 5 buttons apply on drop).
 */
export function canAcceptChild(
  parentType: ComponentType | null,
  childType: ComponentType,
): boolean {
  if (parentType === null) return childType === 17;
  switch (parentType) {
    case 17:
      return childType !== 17;
    case 9:
      return childType === 10 || childType === 2 || childType === 11;
    case 1:
      return childType === 2;
    default:
      return false;
  }
}

export function dropIdFor(parentId: NodeId | null): string {
  return parentId === null ? 'drop-root' : `drop-${parentId}`;
}

export default function DropZone({ parentId, label, compact = false }: DropZoneProps) {
  const parentType = useDocumentStore((s) =>
    parentId === null ? null : (s.doc.nodes[parentId]?.type ?? null),
  );
  const { setNodeRef, isOver } = useDroppable({ id: dropIdFor(parentId) });
  const { active } = useDndContext();

  const current: unknown = active?.data.current;
  let dragType: ComponentType | undefined;
  if (typeof current === 'object' && current !== null && 'componentType' in current) {
    dragType = toComponentType(current.componentType);
  }

  const dragging = dragType !== undefined;
  const valid = dragType !== undefined && canAcceptChild(parentType, dragType);
  const highlight = valid && isOver;
  const text = label ?? 'Drop components here';

  // Invalid zone while dragging: no highlight, just a slim spacer for layout stability.
  if (dragging && !valid) {
    return <div ref={setNodeRef} aria-hidden="true" className="h-1" />;
  }

  return (
    <div
      ref={setNodeRef}
      aria-dropeffect="move"
      aria-label={text}
      className={[
        'flex items-center justify-center rounded-[var(--r-md)] border transition-colors motion-reduce:transition-none',
        compact ? 'min-h-8 px-2 py-1' : 'min-h-12 px-3 py-2',
        highlight
          ? 'border-dashed border-[var(--brand-blurple)] bg-[var(--bg-elevated)]'
          : valid
            ? 'border-dashed border-[var(--brand-blurple)] opacity-70'
            : 'border-dashed border-[var(--border-subtle)]',
      ].join(' ')}
    >
      <span
        className={[
          'text-xs',
          highlight || valid ? 'text-[var(--text-primary)]' : 'text-[var(--text-muted)]',
        ].join(' ')}
      >
        {dragging ? text : 'Drop components here'}
      </span>
    </div>
  );
}
